"""add user_book_logs table

Revision ID: d0c1546b361a
Revises: 71d8b18c00c8
Create Date: 2026-08-09 11:53:57.818148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c1546b361a'
down_revision: Union[str, Sequence[str], None] = '71d8b18c00c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_book_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('norm_title', sa.String(), nullable=False),
    sa.Column('volume_info', sa.String(), nullable=True),
    sa.Column('author_or_publisher', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'norm_title', 'status', name='uq_user_booklog_entry')
    )
    op.create_index(op.f('ix_user_book_logs_id'), 'user_book_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_book_logs_norm_title'), 'user_book_logs', ['norm_title'], unique=False)
    op.create_index(op.f('ix_user_book_logs_status'), 'user_book_logs', ['status'], unique=False)
    op.create_index(op.f('ix_user_book_logs_user_id'), 'user_book_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_book_logs_user_id'), table_name='user_book_logs')
    op.drop_index(op.f('ix_user_book_logs_status'), table_name='user_book_logs')
    op.drop_index(op.f('ix_user_book_logs_norm_title'), table_name='user_book_logs')
    op.drop_index(op.f('ix_user_book_logs_id'), table_name='user_book_logs')
    op.drop_table('user_book_logs')
    # ### end Alembic commands ###
